### ISSUE TITLE
doesn't seem to be working - global modules

### ISSUE THREAD

**Issue by skandasoft** [substack/node-resolve#68]
In the node prompt I typed

```
require('resolve').sync('gulp')

Error: Cannot find module 'gulp' from '.'
    at Function.module.exports [as sync] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\resolve\lib\sync.js:33:11)
    at repl:1:21
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.EventEmitter.emit (events.js:98:17)
```

But I am able to require gulp from node...This is a global module..

**Comment by nantunes** [comment]
I'm experiencing the same issue.

**Comment by vivanov1410** [comment]
+1

**Comment by ljharb** [comment]
You can't require global modules, as such, `resolve` (just like `require.resolve`) shouldn't be able to find them.

@skandasoft do you have `$NODE_PATH` set to `npm root -g`? If so, that would enable `node` to `require` your global modules, but since that's a hugely deprecated bad practice, `resolve` wouldn't support that automatically.

However, you can pass a `__basedir` option to `resolve` set to `process.env.NODE_PATH` and it might be able to find it.
